# Generated by Django 5.0.6 on 2024-06-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaranti', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='empfname',
            field=models.CharField(default='FirstName', max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='empid',
            field=models.CharField(default='EMP0001', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='emplname',
            field=models.CharField(default='LastName', max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='emppasswd',
            field=models.CharField(default='password', max_length=256),
        ),
        migrations.AddField(
            model_name='employee',
            name='emprole',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
